Find and compare
bryanesong/FoodAppProject pull request #8
Opened 2021-09-26 02:50 UTC by IMlame

created route that finds nearby restaurants and orders them by their comparability score

2021-09-26 06:21 UTC, bryanesong commented on routes/routes.py
> +@app.route("/restaurants/search_and_find", methods=["GET"])
So this method takes in a resturant and its location and returns similar resturants. What is the search radius? Is it defaulted?

2021-09-26 06:40 UTC, bryanesong requested changes
need small changes to re-design route

2021-09-28 06:46 UTC, IMlame commented
As far as I could tell, there is no way to specify the search radius of nearby restaurants through the yelp api.

2021-10-21 01:39 UTC, bryanesong approved these changes
lgtm!

2021-10-21 01:39 UTC, merged